// booksTwId = 博客來產品編號，用於載入封面圖
// isbn      = 國際書號，作為 Google Books API 備援搜尋
const BOOKS = [
  {
    id: "book-01",
    title: "給我40歲的女兒",
    author: "韓星姬",
    translator: "Lou 譯",
    publisher: "商業周刊",
    category: "心理",
    tags: ["心理", "親子", "女性"],
    booksTwId: "0010998401",
    summary: "韓國資深心理諮詢師以母親的身份，寫給正值40歲人生關鍵期的女兒。書中涵蓋婚姻、職場、友誼與自我認同等議題，以溫柔而睿智的筆觸引導讀者在中年的人生岔路口找到方向與勇氣。作者根據多年諮詢經驗整理出38個提醒，幫助走過中年之路的女性重新認識自己、珍視自身的價值。",
    highlight: "38個給中年女性的人生智慧提醒",
    color: "#3B6EA5"
  },
  {
    id: "book-02",
    title: "陪伴心理學",
    author: "黃士鈞（哈克）",
    publisher: "天下文化",
    category: "心理",
    tags: ["心理", "人際", "助人"],
    booksTwId: "0010941911",
    summary: "深入探討人與人之間「陪伴」的藝術，以心理學的角度分析如何真正理解他人的需求，建立深刻而有意義的關係。黃士鈞（哈克）以其豐富的心理諮詢經驗，揭示陪伴不只是在場，而是一種深刻的心靈連結。適合助人工作者及想改善人際關係的所有讀者。",
    highlight: "學習真正「在場」的陪伴藝術",
    color: "#7B3F2E"
  },
  {
    id: "book-03",
    title: "帥過頭傳奇：不想平凡",
    author: "劉豪竑",
    publisher: "水靈文創",
    category: "勵志",
    tags: ["勵志", "傳記", "創業"],
    isbn: "9789869969185",
    summary: "記錄一位不甘平凡的創業者如何突破自我限制，在充滿挑戰的環境中找到成功之道。作者透過親身採訪劉豪竑，呈現他從默默無名到闖出一片天的心路歷程，充滿激勵人心的故事與實用的人生智慧。適合正在尋找人生突破口的讀者。",
    highlight: "從平凡到非凡的真實蛻變故事",
    color: "#2E6B3E"
  },
  {
    id: "book-04",
    title: "自慢（康建全部生命系列 09）",
    author: "楊定一",
    publisher: "天下雜誌",
    category: "心靈",
    tags: ["心靈", "自信", "生命哲學"],
    googleQuery: "自慢 楊定一",
    summary: "楊定一博士帶領讀者重新思考「自信」的本質，探索真正的自我認知如何成為人生的力量。結合東西方哲學與現代科學，揭示生命的深層智慧。書中引導讀者放下外在評價，回歸內心真實的自我，找到屬於自己的定靜之道，在紛亂的世界中安住當下。",
    highlight: "回歸內心，找到真正的自我定靜",
    color: "#4A5568"
  },
  {
    id: "book-05",
    title: "不生病的藏傳煉心術",
    author: "洛桑加參",
    publisher: "天下生活",
    category: "健康",
    tags: ["健康", "藏醫", "身心靈"],
    booksTwId: "0010939508",
    summary: "藏醫師洛桑加參結合傳統藏醫學與現代醫學，分享如何透過心靈修練達到身心健康。書中提供具體的冥想、飲食與生活習慣建議，幫助讀者建立健康的內在醫學觀。護你身心均安的內在醫學，讓身體自癒力覺醒，從根本解決文明病困擾。",
    highlight: "藏傳醫學智慧：啟動身體的自癒能力",
    color: "#2D6A4F"
  },
  {
    id: "book-06",
    title: "心轉，病自癒",
    author: "蔡松彥 醫師",
    publisher: "原水文化",
    category: "健康",
    tags: ["健康", "身心", "自癒"],
    booksTwId: "0010932369",
    summary: "記錄蔡維心的健康逆齡奇蹟，探討正面心態如何影響身體健康。從醫學角度分析身心連結的科學原理，提供真實案例說明意念與情緒對疾病預防和康復的重要性。神經科醫師蔡松彥以五維一心理論揭示身體自癒的深層機制。",
    highlight: "真實案例：心念如何逆轉疾病",
    color: "#2563EB"
  },
  {
    id: "book-07",
    title: "金剛經白話講述",
    author: "王思迅",
    publisher: "橡實文化",
    category: "宗教",
    tags: ["佛學", "宗教", "禪修"],
    googleQuery: "金剛經白話 王思迅",
    summary: "以現代白話文深入淺出地詮釋佛教重要經典《金剛經》，引導讀者理解「放下」的智慧。透過生活化的例子，將古老的佛法智慧轉化為現代人可實踐的人生修行之道。適合對佛學有興趣但不熟悉文言文的讀者，是入門金剛經的絕佳選擇。",
    highlight: "白話解讀金剛經，讓放下成為日常修行",
    color: "#1E40AF"
  },
  {
    id: "book-08",
    title: "The Joys of Compounding",
    author: "Gautam Baid",
    publisher: "Columbia Business School Publishing",
    category: "投資",
    tags: ["投資", "財務", "英文"],
    booksTwId: "F015677746",
    isbn: "9780231197328",
    summary: "A profound exploration of how the principle of compounding applies not just to investments, but to knowledge, relationships, and character. Drawing wisdom from investing legends like Warren Buffett and Charlie Munger, this book offers timeless principles for living a fulfilling and prosperous life. It bridges the gap between investment philosophy and personal development.",
    highlight: "Compounding wisdom: from investing to life philosophy",
    color: "#1D4ED8"
  },
  {
    id: "book-09",
    title: "複利的喜悅",
    author: "Gautam Baid 著 / 高塔姆・白德",
    publisher: "天下雜誌",
    category: "投資",
    tags: ["投資", "財務", "複利"],
    booksTwId: "0010989861",
    summary: "從價值投資到人生決策，啟發巴菲特、蒙格等投資典範的穩健致富金律。探討複利思維如何應用於生活的各個層面，幫助讀者建立長遠眼光，在投資與人生中都能持續成長。本書將投資智慧延伸至自我修練、知識積累與品格養成，是一本難得的身心財富指南。",
    highlight: "複利不只用於理財，更是人生成長的核心法則",
    color: "#374151"
  },

  // ── 第二批書籍 ─────────────────────────────────────────

  {
    id: "book-10",
    title: "一生衣事：訂製未來的自己",
    author: "李卿",
    publisher: "木馬文化（靚點 04）",
    category: "時尚",
    tags: ["時尚", "生活風格", "自我成長"],
    googleQuery: "一生衣事 李卿",
    summary: "時尚不只是穿衣服，更是一種生命態度的展現。作者李卿以多年造型美學經驗出發，引導讀者透過服裝風格的選擇，逐步找到屬於自己的人生定位。書中結合心理學與美學觀點，說明外在形象如何影響內在自信，並提供實用的穿搭哲學，幫助讀者「訂製未來的自己」。",
    highlight: "穿出風格，就是在訂製你的人生劇本",
    color: "#7C9BAE"
  },
  {
    id: "book-11",
    title: "全息人生：富能量",
    author: "大俠武林",
    publisher: "韓情文化（Rich 058）",
    category: "投資",
    tags: ["投資", "財務自由", "存股"],
    booksTwId: "0010953131",
    summary: "投資達人大俠武林分享他如何專注本業、用閒錢投資，以「COVER你一生」為目標的全息理財思維。書中涵蓋股票、存股、被動收入等核心概念，強調用正確的心態和系統化方法，讓普通上班族也能透過投資逐步累積財富，打造股市印鈔機。",
    highlight: "專注本業＋閒錢投資，讓股息 COVER 你一輩子",
    color: "#1E3A5F"
  },
  {
    id: "book-12",
    title: "巴菲特的長勝價值",
    author: "Robert G. Hagstrom 著 / 朱崇旻 譯",
    publisher: "遠流（Yulb 實戰智慧 531）",
    category: "投資",
    tags: ["投資", "巴菲特", "價值投資"],
    booksTwId: "0011000957",
    isbn: "9786263619265",
    summary: "深入剖析「股神」華倫・巴菲特的投資思維與決策哲學。作者 Hagstrom 彙整巴菲特數十年的投資歷程，整理出洞悉最偉大投資人金頭腦的七個核心哲學，包含如何選股、評估企業內在價值、長期持有的耐心等。是想深入了解價值投資者不可錯過的經典之作。",
    highlight: "洞悉巴菲特的7個投資哲學，勝券在握",
    color: "#3D1F0A"
  },
  {
    id: "book-13",
    title: "麥吉爾腰背脊修復手冊",
    author: "Stuart McGill 著",
    publisher: "旗標（Strength and Conditioning 02）",
    category: "健康",
    tags: ["健康", "運動", "復健", "英文"],
    googleQuery: "Back Mechanic Stuart McGill",
    summary: "加拿大脊椎生物力學權威 Stuart McGill 博士的重要著作中文版。書中以科學實證為基礎，教導讀者如何正確評估背痛原因，透過精準的核心訓練動作與生活習慣調整，從根本消除腰背疼痛。內容涵蓋脊椎解剖學基礎、常見錯誤動作解析，以及循序漸進的復健計畫。",
    highlight: "脊椎權威的科學方法，永久告別腰背痛",
    color: "#4A5568"
  },
  {
    id: "book-14",
    title: "剛剛好的優雅：志玲姊姊修養之道",
    author: "林志玲（ChiLing）",
    publisher: "Smart 智富",
    category: "生活",
    tags: ["生活風格", "自我修養", "勵志"],
    booksTwId: "0010924763",
    summary: "林志玲以「剛剛好」為核心理念，分享她在演藝生涯與生活中淬煉出的修養哲學。書中涵蓋如何維持優雅的心態面對壓力、與人相處的溫柔之道，以及在忙碌生活中保持身心平衡的實踐方法。文字真誠溫暖，傳遞一種不過度、不將就的生活美學。",
    highlight: "不過度也不將就——「剛剛好」才是真優雅",
    color: "#C4A0A0"
  },
  {
    id: "book-15",
    title: "超簡單買低賣高投資術",
    author: "孫慶龍",
    publisher: "Smart 智富",
    category: "投資",
    tags: ["投資", "股票", "ETF", "存股"],
    booksTwId: "0010967906",
    summary: "專為投資新手設計的實戰入門書。作者孫慶龍以淺顯易懂的方式，系統化說明如何判斷買低賣高的時機，並整合飆股選股、長期存股與 ETF 被動投資三種策略，讓讀者一次掌握不同市場環境下的應對方法，建立屬於自己的投資系統。",
    highlight: "飆股、存股、ETF 三策略一次學會",
    color: "#B91C1C"
  },
  {
    id: "book-16",
    title: "艾蜜莉教你自動化存股",
    author: "艾蜜莉（陳思聖）",
    publisher: "Smart 智富",
    category: "投資",
    tags: ["投資", "存股", "小資族", "自動化"],
    booksTwId: "0010728435",
    summary: "人氣財經部落客艾蜜莉以自身小資族存股經驗，教導讀者如何建立一套「自動化存股」系統。書中說明如何篩選體質健全的好公司、設定合理買進價格，以及透過紀律執行讓複利自動滾雪球，目標讓小資族也能年化報酬達 15%，逐步邁向財務自由。",
    highlight: "小資族也能靠自動化存股年賺 15%",
    color: "#1E3A5F"
  },
  {
    id: "book-17",
    title: "股息 Cover 我每一天",
    author: "大俠武林",
    publisher: "Smart 智富",
    category: "投資",
    tags: ["投資", "股息", "存股", "財務自由"],
    booksTwId: "0010898998",
    summary: "投資達人大俠武林分享如何透過長期存股累積股息，讓被動收入逐漸覆蓋日常生活開銷，實現「股息 Cover 每一天」的財務自由目標。書中揭示他的選股邏輯、持股心態與面對市場波動的應對策略，是存股族最實用的操作指南。",
    highlight: "用股息覆蓋生活費，讓錢替你工作每一天",
    color: "#D97706"
  },
  {
    id: "book-18",
    title: "清淨的信心",
    author: "聖嚴法師",
    publisher: "法鼓文化（花語文說心 2）",
    category: "宗教",
    tags: ["佛學", "宗教", "心靈", "禪修"],
    googleQuery: "清淨的信心 聖嚴",
    summary: "聖嚴法師以簡明溫潤的語言，引導讀者認識「信心」在佛法修行中的核心地位。書中探討如何在日常生活中培養清淨的信念，放下執著與雜念，讓心回歸平靜與清明。適合對佛法感興趣或尋求內心安定的讀者，文字清淺易懂，充滿實踐智慧。",
    highlight: "以清淨信心為基，讓日常即是修行道場",
    color: "#6B7280"
  },

  // ── 第三批書籍（新書上架）───────────────────────────────
  {
    id: "book-19",
    title: "百菜餅機料理",
    author: "百道料理編輯部",
    publisher: "上旗文化",
    category: "生活",
    tags: ["料理", "生活", "健康"],
    googleQuery: "百菜餅機料理 上旗",
    summary: "以鬆餅機為核心器具，收錄百道創意料理食譜，涵蓋早午餐、甜點、鹹食等多元類型。每道食譜步驟清晰、材料易取得，讓廚房新手也能輕鬆上手，用一台機器做出豐富多彩的餐桌風景。",
    highlight: "一台餅機，百種可能——讓料理變得簡單有趣",
    color: "#C4704E"
  },
  {
    id: "book-20",
    title: "LINE官方帳號2.0 通向百萬星級店家（修訂版）",
    author: "周宗義、劉道德、郭品志",
    publisher: "碁峰（GOTOP）",
    category: "商業",
    tags: ["商業", "行銷", "社群", "LINE"],
    googleQuery: "LINE官方帳號2.0 通向百萬星級店家",
    summary: "全面解析LINE官方帳號2.0的功能與操作策略，從帳號設定、訊息設計到自動化行銷，幫助店家善用LINE生態系建立忠實顧客群。書中收錄真實店家的成功案例與數據分析，指引中小企業突破百萬粉絲門檻，打造高黏著度的品牌社群。",
    highlight: "掌握LINE 2.0，讓每個訊息都成為業績轉換機",
    color: "#00C300"
  },
  {
    id: "book-21",
    title: "健康由脊椎開始",
    author: "侯鐘堡",
    publisher: "晨星",
    category: "健康",
    tags: ["健康", "脊椎", "復健", "姿勢"],
    googleQuery: "健康由脊椎開始 侯鐘堡",
    summary: "脊椎是人體健康的核心支柱，許多慢性病與日常不適都源自脊椎問題。本書從解剖學出發，深入淺出地解說脊椎構造、常見傷害成因，並提供改善姿勢、強化核心肌群的實用方法，幫助讀者從根本找回健康體態。",
    highlight: "脊椎正，百病不侵——從姿勢開始的健康革命",
    color: "#4A7C59"
  },
  {
    id: "book-22",
    title: "別把你的錢留到死",
    author: "比爾・柏金斯（Bill Perkins）著／李芳齡 譯",
    publisher: "城邦商業周刊",
    category: "投資",
    tags: ["投資", "理財", "人生規劃", "消費"],
    booksTwId: "0010968401",
    summary: "你存了一輩子的錢，卻可能在最能享受的年紀不捨得花。本書打破傳統理財觀念，主張「人生最重要的投資是購買體驗」，教你在對的時間、對的年齡花掉應花的錢，將金錢轉化為最有意義的人生記憶，而非留到死去那天還有帳戶餘額。",
    highlight: "別讓錢成為人生的囚籠——學會在對的時機大膽消費",
    color: "#1E3A5F"
  },
  {
    id: "book-23",
    title: "我不餓，但我就是想吃",
    author: "賈德森・布魯爾（Judson Brewer）著／謝明珊 譯",
    publisher: "天下文化",
    category: "心理",
    tags: ["心理", "飲食", "習慣", "正念"],
    booksTwId: "0010939001",
    summary: "明明不餓，為何還是想吃？本書從神經科學與正念角度解析飲食衝動的根源，揭示大腦的獎勵迴路如何驅動我們的進食行為。作者布魯爾博士提供具體可行的方法，幫助讀者打破「壓力→渴望→進食」的惡性循環，與食物建立更健康的關係。",
    highlight: "了解大腦的飢餓密碼，從根本改變飲食衝動",
    color: "#7C5C8A"
  },
  {
    id: "book-24",
    title: "工作好修行",
    author: "枡野俊明",
    publisher: "橡實文化",
    category: "勵志",
    tags: ["勵志", "職場", "禪修", "生活哲學"],
    googleQuery: "工作好修行 枡野俊明",
    summary: "日本禪僧兼建築師枡野俊明以禪的智慧詮釋工作的本質，主張每一份工作都是修行的場域。書中分享如何在繁忙職場中保持清明心境、以專注與感恩面對每項任務，讓工作不再是負擔，而成為淨化心靈、實現自我的修行之路。",
    highlight: "把工作當修行，每個任務都是人生道場",
    color: "#4A5568"
  },
  {
    id: "book-25",
    title: "1天1行小日記，讓我超強行動力",
    author: "江季芸",
    publisher: "采實文化",
    category: "勵志",
    tags: ["勵志", "習慣", "行動力", "日記"],
    booksTwId: "0010952801",
    summary: "每天只需一行字，卻能累積強大的行動力。本書以「微習慣」理論為基礎，分享透過簡短日記記錄目標進展、反思每日得失的實踐方法。作者親身驗證一年365天的微小記錄如何逐步改變思維模式，讓夢想從紙上走入真實生活。",
    highlight: "每天一行，積累365天的人生改變",
    color: "#D97706"
  },
  {
    id: "book-26",
    title: "波段存股法，讓我滾出千萬退休金",
    author: "林茂昌",
    publisher: "采實文化",
    category: "投資",
    tags: ["投資", "存股", "退休", "波段"],
    booksTwId: "0010946205",
    summary: "結合「存股」的穩健與「波段」的效率，作者分享一套適合一般上班族的複合投資策略。書中詳解如何挑選優質股票、判斷進出場時機，以及利用市場波動放大複利效果，目標在退休前滾出人生第一個千萬。",
    highlight: "存股＋波段雙引擎，加速累積退休金",
    color: "#065F46"
  },
  {
    id: "book-27",
    title: "療癒的飲食與斷食：新時代的個人營養學",
    author: "楊定一",
    publisher: "天下生活（康建全部生命系列 26）",
    category: "健康",
    tags: ["健康", "飲食", "斷食", "營養"],
    googleQuery: "療癒的飲食與斷食 楊定一",
    summary: "楊定一博士融合東西方醫學智慧，深入探討飲食結構與身心健康的深層關係。書中介紹間歇性斷食、抗炎飲食、腸道微生物等最新科學研究，並提供個人化的營養策略，引導讀者透過調整飲食找回身體的自癒力與生命活力。",
    highlight: "食物即藥物——用飲食啟動身體深層療癒",
    color: "#2D6A4F"
  },
  {
    id: "book-28",
    title: "如何在LINE、FB寫出爆文案",
    author: "周佑勳",
    publisher: "時報出版（Business 036）",
    category: "商業",
    tags: ["商業", "文案", "行銷", "社群"],
    googleQuery: "如何在LINE FB寫出爆文案 周佑勳",
    summary: "專為中小企業主與行銷人員設計的社群文案實戰指南。作者歸納出在LINE群組與Facebook上引爆分享的文案公式，從標題撰寫、情緒觸發到行動呼籲，提供完整的寫作框架與真實案例分析，讓每一篇貼文都具備病毒傳播的潛力。",
    highlight: "掌握社群文案公式，讓每篇貼文都能瘋傳",
    color: "#BE123C"
  },
  {
    id: "book-29",
    title: "靜心的優雅與節奏",
    author: "王柏元",
    publisher: "圓神出版",
    category: "心靈",
    tags: ["心靈", "靜心", "冥想", "生活美學"],
    googleQuery: "靜心的優雅與節奏 王柏元",
    summary: "在快節奏的現代生活中，靜心是一門需要重新學習的藝術。本書以詩意的文字帶領讀者探索靜心的不同面向，從呼吸、音樂、自然到日常儀式，找到屬於自己的靜定節奏，讓每一刻都成為回歸自我的機會，活出優雅從容的生命質感。",
    highlight: "靜下來，才能聽見生命最美的旋律",
    color: "#6B7F5C"
  },
  {
    id: "book-30",
    title: "其實，你不是你以為的自己",
    author: "重整家",
    publisher: "關鍵明今（圓智出版）",
    category: "心理",
    tags: ["心理", "自我認識", "療癒", "關係"],
    googleQuery: "其實你不是你以為的自己 重整家",
    summary: "我們對自己的認識，有多少是真實的，又有多少來自他人的眼光與評價？本書深入探討「自我概念」的形成機制，幫助讀者看清那些隱藏在習慣、關係與情緒背後的真實面貌，從而鬆動固化的自我設限，找回更自由、更完整的自己。",
    highlight: "拆解自我設限的枷鎖，活出真正的自己",
    color: "#5B6FAD"
  },
  {
    id: "book-31",
    title: "人性的弱點",
    author: "戴爾・卡內基（Dale Carnegie）著／陳彥銘 譯",
    publisher: "龍齡出版（商周出版）",
    category: "心理",
    tags: ["心理", "人際", "溝通", "影響力"],
    booksTwId: "0010969501",
    summary: "出版逾80年、全球暢銷3000萬冊的人際關係經典。卡內基以生動的真實案例，系統性地整理出贏得朋友、影響他人的核心原則。從真誠讚美、傾聽他人到化解衝突，每一個原則都簡單可行，幫助讀者在工作與生活中建立更深刻、更有意義的人際連結。",
    highlight: "80年來改變千萬人際關係的不朽經典",
    color: "#3B1F0A"
  },
  {
    id: "book-32",
    title: "讓愛成為一種能力",
    author: "吳若權",
    publisher: "方智出版",
    category: "心靈",
    tags: ["心靈", "愛", "關係", "情感"],
    googleQuery: "讓愛成為一種能力 吳若權",
    summary: "愛不只是感受，更是一種需要學習的能力。吳若權以溫暖細膩的文筆，分享如何在親密關係、親子關係與自我關係中練習真正的愛——既不委屈自己，也不傷害他人。書中提供具體的情感練習，幫助讀者建立更健康、更豐盛的愛的能力。",
    highlight: "真正的愛，是愛自己，也是懂得愛人",
    color: "#C05A7A"
  },
  {
    id: "book-33",
    title: "YouTube成功的實踐法則60",
    author: "黃上慈、黃元元",
    publisher: "方智出版（dp 極地出版 3）",
    category: "商業",
    tags: ["商業", "YouTube", "影音行銷", "創作"],
    googleQuery: "YouTube成功的實踐法則60",
    summary: "YouTube頻道突破10萬訂閱的60個實戰秘訣全公開。從頻道定位、影片腳本規劃到SEO關鍵字策略，本書系統化整理台灣頻道主最容易忽略的關鍵成功因子，搭配真實數據案例，幫助創作者少走彎路，快速找到頻道成長的飛輪效應。",
    highlight: "60個行動清單，帶你的頻道突破訂閱瓶頸",
    color: "#991B1B"
  },
  {
    id: "book-34",
    title: "運動功能修復全書",
    author: "木村嘉人／勁草書房 著",
    publisher: "方智出版",
    category: "健康",
    tags: ["健康", "運動", "復健", "物理治療"],
    googleQuery: "運動功能修復全書",
    summary: "由日本物理治療師與運動醫學專家共同撰寫，針對現代人常見的肩頸、腰背、膝蓋等運動傷害，提供系統化的評估方法與修復訓練計畫。書中涵蓋60個精確的功能性訓練動作，附有詳細圖解，適合運動員、上班族及復健期患者使用。",
    highlight: "60個精準動作，全面修復身體機能",
    color: "#1E6B4A"
  },
  {
    id: "book-35",
    title: "生活彩虹",
    author: "林方毅",
    publisher: "博明研究院",
    category: "生活",
    tags: ["心靈", "生活", "散文", "正能量"],
    googleQuery: "生活彩虹 林方毅",
    summary: "以彩虹為隱喻，記錄生活中七種不同色彩的情感與體驗。文字清雅流暢，從日常小事出發，探尋人與自然、人與人之間的深刻連結。適合在忙碌日常中尋找片刻寧靜的讀者，每篇短文都如一束光，照進生命的某個角落。",
    highlight: "在日常的縫隙裡，找到生命的七種色彩",
    color: "#7C3AED"
  },
  {
    id: "book-36",
    title: "復健諮商手冊：全人生涯開展",
    author: "林真平、許世穎、許清陽 等著",
    publisher: "心理出版社（諮商輔導系列 73）",
    category: "健康",
    tags: ["健康", "復健", "諮商", "身心障礙"],
    googleQuery: "復健諮商手冊 全人生涯開展",
    summary: "提供復健諮商師、社工及相關醫療人員完整的專業指引，涵蓋障礙評估、職業復健、心理支持與社會融合等面向。以「全人」觀點整合醫療、心理與社會資源，協助身心障礙者在復健過程中實現最大潛能，重建有意義的生涯發展路徑。",
    highlight: "以全人視角，開展每一位復健者的生命可能",
    color: "#374151"
  },
  {
    id: "book-37",
    title: "Be Yourself: Ubermensch — The Birth of New Civilization",
    author: "Harry Selby",
    publisher: "White Rabbit Culture",
    category: "英文",
    tags: ["英文", "哲學", "自我", "文明"],
    googleQuery: "Ubermensch Birth of New Civilization",
    summary: "An exploration of Nietzsche's concept of the Übermensch reinterpreted for the modern era. The book argues that true civilization begins with individuals who dare to transcend convention, cultivate authentic selfhood, and contribute to a higher collective vision. A philosophical call to action for those who wish to live deliberately and creatively.",
    highlight: "To become yourself fully is to birth a new world",
    color: "#1F2937"
  },
  {
    id: "book-38",
    title: "新文明的誕生",
    author: "白兔文化",
    publisher: "白兔文化",
    category: "心靈",
    tags: ["心靈", "文明", "哲學", "人類發展"],
    googleQuery: "新文明的誕生 白兔文化",
    summary: "探討人類文明在科技、意識與精神層面的下一步演化。本書從東西方哲學、靈性傳統與現代科學的交匯點切入，描繪一個以覺知、共融與永續為核心的新文明藍圖，邀請讀者共同思考：在舊秩序瓦解之際，我們能共同建造什麼樣的未來？",
    highlight: "每個覺醒的個體，都是新文明的一塊基石",
    color: "#312E81"
  },
  {
    id: "book-39",
    title: "喚醒自癒力",
    author: "楊定一",
    publisher: "天下生活（康健人生 215）",
    category: "健康",
    tags: ["健康", "自癒", "身心靈", "整合醫學"],
    googleQuery: "喚醒自癒力 楊定一 康健",
    summary: "楊定一博士以科學與靈性的雙重視角，深入探討人體與生俱來的自我療癒潛能。書中整合神經科學、量子生物學與東方冥想智慧，提供一套系統性的身心修練方法，幫助讀者釋放潛藏的自癒力，從根本改善慢性疲勞、免疫失調等現代文明病。",
    highlight: "你的身體本自具足療癒的能力——等待你去喚醒",
    color: "#166534"
  },
  {
    id: "book-40",
    title: "張忠謀自傳（上下冊合集）",
    author: "張忠謀",
    publisher: "天下文化・遠見",
    category: "勵志",
    tags: ["勵志", "傳記", "商業", "半導體"],
    booksTwId: "0010896011",
    summary: "台積電創辦人張忠謀親筆撰寫的完整生命史，上冊記錄1931年至1964年的成長與求學歷程，下冊涵蓋1964年至2018年的創業傳奇。從上海少年到半導體教父，張忠謀以誠懇直率的文字，分享他面對挫折、抉擇與成就的心路歷程，是台灣商業史上不可或缺的重要文獻。",
    highlight: "台積電教父的完整人生：從零建立半導體帝國的真實告白",
    color: "#1E1E2E"
  },
  {
    id: "book-41",
    title: "正念減壓8堂課",
    author: "石世明",
    publisher: "天下文化（照護疾病明讀 002）",
    category: "健康",
    tags: ["健康", "正念", "減壓", "冥想"],
    googleQuery: "正念減壓8堂課 石世明",
    summary: "以卡巴金博士MBSR課程為基礎，由臨床心理師石世明設計的中文版八週正念減壓實踐計畫。每堂課包含核心概念解說、冥想練習指引與日常生活應用，幫助讀者系統性地建立正念能力，有效降低慢性壓力、改善睡眠品質、緩解焦慮與憂鬱情緒。",
    highlight: "八週系統訓練，讓正念成為對抗壓力的日常武器",
    color: "#065F46"
  },
  {
    id: "book-42",
    title: "0050+台股基金超額獲利很簡單！",
    author: "盧燕俐",
    publisher: "治邦文化（天下文化）",
    category: "投資",
    tags: ["投資", "ETF", "台股", "基金"],
    googleQuery: "0050台股基金超額獲利很簡單 盧燕俐",
    summary: "財經專家盧燕俐以多年實戰經驗，提出結合ETF（0050）與主動型基金的「存股部署」新概念，說明如何在台股市場用最簡單的方式達到超額報酬。書中破解「存股不如存台積」的迷思，教讀者用科學方法選股配置，讓投資組合更穩健高效。",
    highlight: "把0050當核心，用基金追求超額——讓投資省力更賺錢",
    color: "#B91C1C"
  },
  {
    id: "book-43",
    title: "莊子，從心開始",
    author: "蔡璧名",
    publisher: "天下（美好生活 007）",
    category: "心靈",
    tags: ["心靈", "莊子", "哲學", "古典"],
    booksTwId: "0010970201",
    summary: "台大中文系教授蔡璧名以現代人的生命困境為出發，重新詮釋莊子的逍遙哲學。書中不繞學術彎路，直接從《莊子》中萃取最能撫慰現代靈魂的智慧，幫助讀者在焦慮、失落與迷惘中找到內心的自由與安頓，以「心」為起點重新出發。",
    highlight: "莊子說：心若自由，便無一事是羈絆",
    color: "#92400E"
  },
  {
    id: "book-44",
    title: "一念之轉：四句話改變你的人生",
    author: "拜倫・凱蒂（Byron Katie）著／蔡孟璇 審訂",
    publisher: "奇蹟資訊中心",
    category: "心靈",
    tags: ["心靈", "轉念", "心理療癒", "靜心"],
    isbn: "9789861759043",
    summary: "拜倫・凱蒂的「功課」（The Work）是全球最受歡迎的自我探詢方法之一。透過四個簡單問題和一個換位思考，引導讀者鬆動根深蒂固的信念，看清痛苦的真正根源不在外界，而在自己的念頭。無數人透過這個方法從憂鬱、憤怒與恐懼中解脫，找到內在真正的平靜。",
    highlight: "四個問題，瓦解讓你痛苦的每一個念頭",
    color: "#5B21B6"
  },
  {
    id: "book-45",
    title: "希望每個能一樣的夢",
    author: "庚玉蕙",
    publisher: "九歌出版社",
    category: "心靈",
    tags: ["心靈", "散文", "夢想", "人生"],
    googleQuery: "希望每個能一樣的夢 庚玉蕙",
    summary: "庚玉蕙以溫柔細膩的散文筆觸，書寫對夢想、時間與人與人之間相遇的深情凝視。文字如詩，在平凡日常中尋找生命的微光，讓讀者在閱讀中感受被理解的溫暖，以及對美好的共同嚮往——那份希望每個人都能擁有的，關於愛與夢的心願。",
    highlight: "願每個靈魂都能找到，屬於自己的那道光",
    color: "#9D4E84"
  },
  {
    id: "book-46",
    title: "重整家的愛與傷",
    author: "吳娟瑜",
    publisher: "方智出版社",
    category: "心理",
    tags: ["心理", "家庭", "親子", "療癒"],
    googleQuery: "重整家的愛與傷 吳娟瑜",
    summary: "家是最親近的地方，卻也是愛與傷交織最深的所在。本書探討原生家庭如何影響我們的人際關係與情感模式，並引導讀者溫柔地面對家族創傷，學習在理解中放下，在接納中重生，找到屬於自己的家庭和諧之道。",
    highlight: "在理解家族傷痛中，學會溫柔地放下與重建",
    color: "#5B8C7E"
  }
];

// 根據博客來產品 ID 建構封面 URL
function buildBooksTwCover(id) {
  if (!id) return null;
  const p1 = id.slice(0, 3);
  const p2 = id.slice(3, 6);
  const p3 = id.slice(6, 8);
  return `https://im2.book.com.tw/image/getImage?i=https://www.books.com.tw/img/${p1}/${p2}/${p3}/${id}.jpg&v=1&w=300&h=300`;
}
